@echo off
set /p img=Image Path (including extention): 
set /p song=Song Path (including extention): 
set /p songn=Song Name: 
set /p artist=Artist Name: 
set /p album=Album Name: 
echo [1/9] Generating background from source...
ffmpeg -hide_banner -loglevel quiet -i "%img%" -vf "eq=brightness=-0.1,crop=iw:ih*9/16,scale=1920:1080,boxblur=25" bg.png
echo [2/9] Generating thumbnail from source...
ffmpeg -hide_banner -loglevel quiet -i "%img%" -vf scale=740:740 tn.png
echo [3/9] Overlaying thumbnail to background...
ffmpeg -hide_banner -loglevel quiet -i bg.png -i tn.png -filter_complex "[0:v][1:v]overlay=100:100" main.png
echo [4/9] Overlaying song title text...
ffmpeg -hide_banner -loglevel quiet -i main.png -vf drawtext="fontfile='Roboto-Bold.ttf':text='%songn%':fontcolor=white:fontsize=54:x=w/2:y=((h-text_h)/2)-153" temp.png
echo [5/9] Overlaying artist name text...
ffmpeg -hide_banner -loglevel quiet -i temp.png -vf drawtext="fontfile='Roboto-Regular.ttf':text='%artist%':fontcolor=white:fontsize=45:x=w/2:y=((h-text_h)/2)-27" temp1.png
echo [6/9] Overlaying album name text...
ffmpeg -hide_banner -loglevel quiet -i temp1.png -vf drawtext="fontfile='Roboto-Regular.ttf':text='%album%':fontcolor=white:fontsize=45:x=w/2:y=((h-text_h)/2)+65" final.png
echo [7/9] Deleting temp files...
del bg.png;del tn.png;del main.png;del temp.png;del temp1.png;
echo [8/9] Rendering video with song (CAUTION: USES A LOT OF PROCESSING POWER!)...
ffmpeg -loop 1 -i final.png -i "%song%" -shortest -vf "scale=1920:1080,setsar=1" -r 1 -c:v h264_nvenc -c:a copy "%songn%.mp4"
echo [9/9] Deleting final image...
del final.png
echo Done!
pause